---
version: "3.7"
services:
  sonarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v1.0.0
    command: ["sonarr"]
    environment:
      PORT: 9707
      URL: "http://192.168.1.100:8989"
      APIKEY: "xxx"
      ENABLE_EPISODE_QUALITY_METRICS: "false"
    ports:
      - "9707:9707"
  radarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v1.0.0
    command: ["radarr"]
    environment:
      PORT: 9708
      URL: "http://192.168.1.100:7878"
      APIKEY: "xxx"
    ports:
      - "9708:9708"
  lidarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v1.0.0
    command: ["lidarr"]
    environment:
      PORT: 9709
      URL: "http://192.168.1.100:8686"
      APIKEY: "xxx"
    ports:
      - "9709:9709"
