---
version: "3.7"
services:
  sonarr-exporter:
    image: ghcr.io/onedr0p/exportarr:latest
    command: ["exportarr", "sonarr"]
    environment:
      PORT: 9707
      URL: "http://192.168.1.100:8989"
      APIKEY: "amlmndfb503rfqaa5ln5hj5qkmu3hy18"
      ENABLE_EPISODE_QUALITY_METRICS: "false"
    ports:
      - "9707:9707"
  radarr-exporter:
    image: ghcr.io/onedr0p/exportarr:latest
    command: ["exportarr", "radarr"]
    environment:
      PORT: 9708
      URL: "http://192.168.1.100:7878"
      APIKEY: "zmlmndfb503rfqaa5ln5hj5qkmu3hy19"
    ports:
      - "9708:9708"
  lidarr-exporter:
    image: ghcr.io/onedr0p/exportarr:latest
    command: ["exportarr", "lidarr"]
    environment:
      PORT: 9709
      URL: "http://192.168.1.100:8686"
      APIKEY: "zmlmndfb503rfqaa5ln5hj5qkmu3hy19"
    ports:
      - "9709:9709"
