---
apiVersion: v1
kind: Service
metadata:
  name: lidarr-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: lidarr-exporter
    app.kubernetes.io/instance: lidarr-exporter
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: lidarr-exporter
    app.kubernetes.io/instance: lidarr-exporter
  ports:
  - name: monitoring
    port: 9709
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lidarr-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: lidarr-exporter
    app.kubernetes.io/instance: lidarr-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lidarr-exporter
      app.kubernetes.io/instance: lidarr-exporter
  endpoints:
  - port: monitoring
    interval: 4m
    scrapeTimeout: 1m
    path: /metrics
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: lidarr-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: lidarr-exporter
    app.kubernetes.io/instance: lidarr-exporter
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.lidarr-exporter: semver:~v0
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: lidarr-exporter
      app.kubernetes.io/instance: lidarr-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lidarr-exporter
        app.kubernetes.io/instance: lidarr-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "monitoring"
    spec:
      containers:
      - name: lidarr-exporter
        image: onedr0p/exportarr:v0.1.0
        imagePullPolicy: IfNotPresent
        command: ["exportarr"]
        args: ["lidarr"]
        env:
        - name: LISTEN_PORT
          value: "9709"
        - name: LIDARR_URL
          value: "http://lidarr.default.svc.cluster.local:8686"
        - name: LIDARR_APIKEY
          valueFrom:
            secretKeyRef:
              name: lidarr-exporter
              key: api-key
        ports:
        - name: monitoring
          containerPort: 9709
        livenessProbe:
          httpGet:
            path: /healthz
            port: monitoring
          failureThreshold: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: monitoring
          failureThreshold: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
